dictionaries = [
    "en_gb",
    "en_us",
]
words = [
    "autobuild",
    "breakpoint",
    "clangd",
    "dapui",
    "esc",
    "fillchars",
    "fzf",
    "gitsigns",
    "glsl",
    "javaagent",
    "jdt",
    "jdtls",
    "jdtls's",
    "kanagawa",
    "keymaps",
    "lockb",
    "lualine",
    "mvn",
    "mvnw",
    "neodarcula",
    "neotree",
    "noh",
    "nvim",
    "nvmrc",
    "pnpm",
    "pom",
    "rnu",
    "stdpath",
    "vscode",
    "vscpp",
    "wincmd",
    "zoxide",
]
ignore_patterns = [
    'vim\..*\.\b[a-z]+\b',
    'require\("\b.*\b"\)',
    '\b.*\b\.nvim',
]
